name: Update version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'version.json'

jobs:
  update-version:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip-version]')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write version.json
        run: |
          echo "{ \"commit\": \"$(git rev-parse HEAD)\" }" > version.json

      - name: Commit version.json (silent)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "chore: update version [skip ci]" || exit 0

      - name: Push
        run: git push
